apiVersion: v1
kind: Secret
metadata:
    name: mssql-secret
type: Opaque
data:
    SA_PASSWORD: <base64-encoded-password>

---
apiVersion: v1
kind: Service
metadata:
    name: mssql-service
spec:
    selector:
        app: mssql
    ports:
        - protocol: TCP
            port: 1433
            targetPort: 1433

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mssql
        spec:
            containers:
                - name: mssql
                    image: mcr.microsoft.com/mssql/server:2019-latest
                    ports:
                        - containerPort: 1433
                    env:
                        - name: ACCEPT_EULA
                            value: "Y"
                        - name: SA_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: mssql-secret
                                    key: SA_PASSWORD
                                    volumeMounts:
                                        - name: mssql-data
                                          mountPath: /var/opt/mssql
                            volumes:
                                - name: mssql-data
                                  persistentVolumeClaim:
                                      claimName: mssql-pvc