name: Working with Workflow

on:
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'Home drive on the machine'
        required: true

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
     - name: Check Out
       uses:  actions/checkout@v4.2.2

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: |
           REPO_URL='https://github.com/aboubacardiaby/DomFinAPI.git';
           BRANCH_NAME=main; 
             if [ -z "$BRANCH_NAME" ]; then
             echo "Cloning repository: $REPO_URL";
               git clone "$REPO_URL";
