name: tutorial-workflow

on: [push, workflow_dispatch]

jobs:
  job_1:
    name: this is job number 1
    runs-on: ubuntu-latest
    steps:
     
      - name: Write summary in Action
        uses: actions/github-script@v7.0.1
        with:
          script: |
            await core.summary
              .addHeading('Test Result')
              .addTable([
                [{ data: 'File', header: true }, { data: 'Result', header: true }],
                ['foo.js', 'Pass'],
                ['bar.js', 'Pass'],
                ['Test', 'Pass']
              ])
              .addLink('View Staging Deployment!', 'https://github.com')
              .write()
