name: tutorial workflow

on: [push, workflow_dispatch]

jobs:
 job_1:
   name: this is job number 1
   runs-on: ubuntu-latest
   steps:
     -  name: first step
        run:  |
           the_secret=$((RANDOM))
           echo "::add-mask::$the_secret"
           echo $((RANDOM)) >> $GITHUB_OUTPUT
           echo ":: error file=app.js, line=1 ::missing semicolon"
           echo $GITHUB_OUTPUT
   
